# Generated by Django 3.0.5 on 2024-01-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurnal',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('link', models.CharField(max_length=150)),
                ('abstracturl', models.CharField(max_length=150)),
            ],
        ),
    ]
