# Generated by Django 3.0.5 on 2024-01-04 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_jurnal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
        migrations.AlterModelTable(
            name='jurnal',
            table='tbjurnal',
        ),
    ]
